name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v2

      - name: Deploy DAGs
        run: |
          cd /home/emilegill743/Projects/airflow-dags
          git fetch --all
          git reset --hard origin/master
          
